SCREEN_WIDTH = 667
SCREEN_HEIGHT = 375
GAME_SCREEN_MIDDLE_X = SCREEN_WIDTH // 2
GAME_SCREEN_WIDTH = SCREEN_WIDTH
GAME_SCREEN_HEIGHT = SCREEN_HEIGHT - 40
MAX_TERRAIN_X_OFFSET = 6
BRIDGE_LINE = GAME_SCREEN_HEIGHT * 10
BRIDGE_WIDTH = 85
SETTLEMENT_LINES = 50

Line: int = 0
Area: int = 0
FINAL_AREA: int = 26
CARRIER_LINE: int = BRIDGE_LINE * FINAL_AREA + 3 * GAME_SCREEN_HEIGHT
FINAL_LINE: int = CARRIER_LINE + 600

Screen = None
Scenery = None
Sprites = None

Enemy_Missiles = None
Enemy_Count: int = None

Debugging: bool = False
